experiment_name: "test"
versions: "_v1"
task: "brain_age_prediction"

model:
  model_name: "Imaging_only_brainage"

trainer:
  epochs: 70
  gpu: [1]
  overfit_batches: 0.0  # number between 0 to 1

checkpointing:
  enable: false
  ckpt_dir: "/media/rrtammyfs/Users/daniel/HyperProj_checkpoints"
  continue_train_from_ckpt: false  # either false or the ckpt path


wandb:
  logs_dir: "/home/duenias/PycharmProjects/HyperFusion/wandb_logs"
  project_name: "testing"
  enable: false
  sweep: false


lightning_wrapper:
  wrapper_name: "PlModelWrapBrainAge"

  loss:

  optimizer:
    lr: 0.00015
    weight_decay: 0.05

data_module:
  data_module_name: "BrainAgeDataModule"
  batch_size: 128
  num_workers: 8
  dataset_cfg:
    data_dir: "/data/users/doronser/brain_age"
    metadata_dir: "/home/duenias/PycharmProjects/HyperFusion/Datasets/BrainAgeDataset"
    transform_train:
    transform_valid:
    gender:
    partial_data: 0.5



