wandb_version: 1

GPU:
  desc: null
  value:
  - 1
L2:
  desc: null
  value: 1.0e-05
_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.6.9
    start_time: 1678111619
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 48
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 41
      - 48
      - 53
      - 55
      3:
      - 7
      - 13
      4: 3.6.9
      5: 0.12.17
      8:
      - 5
adni_dir:
  desc: null
  value: /media/rrtammyfs/Users/daniel/adni_class_pred_1x1x1_v1
batch_size:
  desc: null
  value: 4
bn_momentum:
  desc: null
  value: 0.05
checkpoint_dir:
  desc: null
  value: checkpoints
class_names:
  desc: null
  value:
  - CN
  - MCI
  - AD
cnn_dropout:
  desc: null
  value: 0.1
cnn_mlp_dropout:
  desc: null
  value: 0.0
cnn_mlp_shapes:
  desc: null
  value:
  - 3
continue_from_checkpoint:
  desc: null
  value: false
cp_cont_epoch:
  desc: null
  value: 1
data_fold:
  desc: null
  value: 0
dropout:
  desc: null
  value: 0.0
enable_checkpointing:
  desc: null
  value: false
epochs:
  desc: null
  value: 30
experiment_name:
  desc: null
  value: tst
hidden_shapes:
  desc: null
  value:
  - 24
  - 32
  - 5
init_features:
  desc: null
  value: 32
load2ram:
  desc: null
  value: false
logs_dir:
  desc: null
  value: wandb_logs
lr:
  desc: null
  value: 0.0001
metadata_path:
  desc: null
  value: metadata_by_features_sets/set-1.csv
model:
  desc: null
  value: age_noembd_lastblockHyp_FFT_fcHyp_2
num_workers:
  desc: null
  value: 0
overfit_batches:
  desc: null
  value: 0.05
project_name:
  desc: null
  value: HyperNets_imgNtabular
runfromshell:
  desc: null
  value: false
transform:
  desc: null
  value: hippo_crop_lNr
wandb_log:
  desc: null
  value: true
wandb_sweeping:
  desc: null
  value: false
